image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2

stages:
  - build
  - deploy
  - test

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build:
  stage: build
  script:
    - docker build -t $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress1:latest ./wordpress
    - docker build -t $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress2:latest ./wordpress
    - docker build -t $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress3:latest ./wordpress
    - docker build -t $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/mysql:latest ./mysql
    - docker build -t $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/influxdb:latest ./influxdb
    - docker build -t $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/powertop:latest ./powertop
    - docker build -t $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/nginx:latest ./nginx
    - docker push $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress1:latest
    - docker push $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress2:latest
    - docker push $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress3:latest
    - docker push $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/mysql:latest
    - docker push $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/nginx:latest
    - docker push $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/influxdb:latest
    - docker push $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/powertop:latest
  only:
    - main

pull:
  stage: deploy
  script:
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress1
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress2
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress3
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/mysql
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/influxdb
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/nginx
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/powertop
    - docker run --name mysql -d -v db_data:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -e MYSQL_DATABASE=wordpress -e MYSQL_USER=wordpress -e MYSQL_PASSWORD=wordpress $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/mysql
    - docker run --name wordpress1 -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=wordpress -e WORDPRESS_DB_PASSWORD=wordpress -e WORDPRESS_DB_NAME=wordpress -d -p 8081:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress1
    - docker run --name wordpress2 -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=wordpress -e WORDPRESS_DB_PASSWORD=wordpress -e WORDPRESS_DB_NAME=wordpress -d -p 8082:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress2
    - docker run --name wordpress3 -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=wordpress -e WORDPRESS_DB_PASSWORD=wordpress -e WORDPRESS_DB_NAME=wordpress -d -p 8083:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress3
    - docker run --name nginx -d -p 80:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/nginx
    - docker run --name influxdb -d -v influxdb:/var/lib/influxdb -e DOCKER_INFLUXDB_INIT_MODE=setup -e DOCKER_INFLUXDB_INIT_MODE=setup -e DOCKER_INFLUXDB_INIT_USERNAME=admin -e DOCKER_INFLUXDB_INIT_PASSWORD=admin_password -e DOCKER_INFLUXDB_INIT_ORG=my_org -e DOCKER_INFLUXDB_INIT_BUCKET=my_bucket -e DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=my-super-secret-auth-token -p 8086:8086 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/influxdb
    - docker run --name powertop -d -v /var/run/docker.sock:/var/run/docker.sock $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/powertop
  only:
    - main

test_blog:
  stage: test
  script:
    - apk add --no-cache curl
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/mysql
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress1
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress2
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress3
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/nginx
    - docker run --name mysql -e MYSQL_ROOT_PASSWORD=root -e MYSQL_DATABASE=wordpress -e MYSQL_USER=wordpress -e MYSQL_PASSWORD=wordpress -d $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/mysql
    - sleep 30 
    - docker run --name wordpress1 -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=wordpress -e WORDPRESS_DB_PASSWORD=wordpress -e WORDPRESS_DB_NAME=wordpress -d -p 8081:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress1
    - docker run --name wordpress2 -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=wordpress -e WORDPRESS_DB_PASSWORD=wordpress -e WORDPRESS_DB_NAME=wordpress -d -p 8082:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress2
    - docker run --name wordpress3 -e WORDPRESS_DB_HOST=mysql -e WORDPRESS_DB_USER=wordpress -e WORDPRESS_DB_PASSWORD=wordpress -e WORDPRESS_DB_NAME=wordpress -d -p 8083:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/wordpress3
    - docker run --name nginx -d -p 80:80 $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/nginx
    - sleep 30 
    - docker ps
    - >
      if curl -sSf http://localhost:8081; then 
        echo "WordPress 1 is online"; 
      else 
        echo "WordPress 1 is offline"; 
        exit 1; 
      fi
    - >
      if curl -sSf http://localhost:8082; then 
        echo "WordPress 2 is online"; 
      else 
        echo "WordPress 2 is offline"; 
        exit 1; 
      fi
    - >
      if curl -sSf http://localhost:8083; then
        echo "WordPress 3 is online";
      else
        echo "WordPress 3 is offline";
        exit 1;
      fi
    - >
      if curl -sSf http://localhost:80; then
        echo "loadbalancer is online";
      else
        echo "loadbalancer is offline";
        exit 1;
      fi
  only:
    - main

test_pluggin:
  stage: test
  script:
    - docker pull $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/powertop
    - docker run --name powertop -d -v /var/run/docker.sock:/var/run/docker.sock $CI_REGISTRY/irouag/projet_pro-1_ilies_sylvain/powertop
    - apk add --no-cache curl
    - docker ps
    - sleep 60
    - >
      if ! docker ps | grep -q powertop; then 
        docker ps
        exit 1; 
      fi
  only:
    - main
