version: '3.8'

services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "80:80"
    depends_on:
      - wordpress1
      - wordpress2
      - wordpress3

  wordpress1:
    build: ./wordpress
    ports:
      - "8081:80"
    container_name: wordpress1
    depends_on:
      - mysql

    env_file:
      - .env

  wordpress2:
    build: ./wordpress
    ports:
      - "8082:80"
    container_name: wordpress2
    depends_on:
      - mysql
    env_file:
      - .env

  wordpress3:
    build: ./wordpress
    ports:
      - "8083:80"
    container_name: wordpress3
    depends_on:
      - mysql
    env_file:
      - .env

  mysql:
    build: ./mysql
    container_name: mysql
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - .env

  powertop:
    build: ./powertop
    container_name: powertop
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - influxdb
    env_file:
      - .env

  influxdb:
    build: ./influxdb
    ports:
      - "8086:8086"
    container_name: influxdb
    depends_on:
      - nginx
    volumes:
      - influxdb:/var/lib/influxdb
    env_file:
      - .env

volumes:
  influxdb:
  db_data:
